baseurl = "http://www.harveycms.org/"
languageCode = "en-us"
title = "Harvey CMS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Ryan D"
	description = "Harvey CMS | Open Source CMS powered by Go lang and Ember.js"
	copyright = "Ryan D. All Rights Reserved. Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/ryan0x44/harveycms"

	# version = "0.1.0"
	# logo = "images/logo.png"
	# favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["custom.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent = "teal"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "ryan0x44"


[[menu.main]]
	name   = "Welcome"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Concepts"
	url    = "concepts/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Themes"
	url    = "themes/"
	weight = 30

[[menu.main]]
	name   = "Models"
	url    = "models/"
	weight = 40

[[menu.main]]
	name   = "Deployment"
	url    = "deployment/"
	weight = 50

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 70


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
